using Application.Features.Trading.Automation;

namespace Application.Features.Trading.LiveSettings;

public record TradingLiveSettingsConfigDefaults(
    int MinOpportunities,
    int MaxOpportunities,
    int MinimumSentimentScore,
    int MinimumRetestScore,
    int MinimumMinutesFromMarketOpenForEntry,
    int MaximumMinutesFromMarketOpenForEntry,
    decimal MinimumEntryDistanceFromRangeFraction,
    int MaxMinutesBreakoutToRetest,
    decimal StopLossBufferFraction,
    decimal RewardToRiskRatio,
    int OrderQuantity,
    decimal RiskPerTradeFraction,
    decimal BreakEvenAtRMultiple,
    int MaxBarsInTradeBeforeFlatExit,
    int MaxTradesPerDay,
    decimal MaxDailyLossFraction,
    bool UseTrailingStopLoss,
    decimal PartialTakeProfitFraction,
    decimal TrailingStopRiskMultiple,
    bool TrailingStopBreakEvenProtection,
    bool UseRetestValidationAgent,
    bool UseDirectionalIndicatorFilter,
    bool DirectionalIndicatorRequireAll,
    IReadOnlyList<DirectionalIndicatorMode> DirectionalIndicatorModes
);

public record TradingLiveSettingsDto(
    TradingLiveSettingsConfigDefaults ConfigDefaults,
    int? MinOpportunities,
    int? MaxOpportunities,
    int? MinimumSentimentScore,
    int? MinimumRetestScore,
    int? MinimumMinutesFromMarketOpenForEntry,
    int? MaximumMinutesFromMarketOpenForEntry,
    decimal? MinimumEntryDistanceFromRangeFraction,
    int? MaxMinutesBreakoutToRetest,
    decimal? StopLossBufferFraction,
    decimal? RewardToRiskRatio,
    int? OrderQuantity,
    decimal? RiskPerTradeFraction,
    decimal? BreakEvenAtRMultiple,
    int? MaxBarsInTradeBeforeFlatExit,
    int? MaxTradesPerDay,
    decimal? MaxDailyLossFraction,
    bool? UseTrailingStopLoss,
    decimal? PartialTakeProfitFraction,
    decimal? TrailingStopRiskMultiple,
    bool? TrailingStopBreakEvenProtection,
    bool? UseRetestValidationAgent,
    bool? UseDirectionalIndicatorFilter,
    bool? DirectionalIndicatorRequireAll,
    IReadOnlyList<DirectionalIndicatorMode>? DirectionalIndicatorModes
);

public record UpdateTradingLiveSettingsRequest(
    int? MinOpportunities,
    int? MaxOpportunities,
    int? MinimumSentimentScore,
    int? MinimumRetestScore,
    int? MinimumMinutesFromMarketOpenForEntry,
    int? MaximumMinutesFromMarketOpenForEntry,
    decimal? MinimumEntryDistanceFromRangeFraction,
    int? MaxMinutesBreakoutToRetest,
    decimal? StopLossBufferFraction,
    decimal? RewardToRiskRatio,
    int? OrderQuantity,
    decimal? RiskPerTradeFraction,
    decimal? BreakEvenAtRMultiple,
    int? MaxBarsInTradeBeforeFlatExit,
    int? MaxTradesPerDay,
    decimal? MaxDailyLossFraction,
    bool? UseTrailingStopLoss,
    decimal? PartialTakeProfitFraction,
    decimal? TrailingStopRiskMultiple,
    bool? TrailingStopBreakEvenProtection,
    bool? UseRetestValidationAgent,
    bool? UseDirectionalIndicatorFilter,
    bool? DirectionalIndicatorRequireAll,
    IReadOnlyList<DirectionalIndicatorMode>? DirectionalIndicatorModes
);
