version: '3.9'

services:
  api:
    image: ghcr.io/ger-sportnest/sportnest-backend:latest
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgresDB;Username=postgresUser;Password=postgresPW
    depends_on:
      - postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - DOCKER_CONFIG=/
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_LABEL_ENABLE=true

  postgres:
    image: postgres:16
    container_name: myPostgresDb
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_DB: postgresDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
