// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424101608_ImproveTradingDataQuality")]
    partial class ImproveTradingDataQuality
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasColumnType("text")
                        .HasColumnName("attachment_type");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("attachment_url");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_message");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_message_chat_room_id");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("ix_chat_message_reply_to_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_message_user_id");

                    b.ToTable("chat_message", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_direct");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_chat_room");

                    b.ToTable("chat_room", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoomUser", b =>
                {
                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("ChatRoomId", "UserId")
                        .HasName("pk_chat_room_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_room_user_user_id");

                    b.ToTable("chat_room_user", "public");
                });

            modelBuilder.Entity("Domain.Entities.ExceptionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CaptureKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capture_kind");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("exception_type");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_handled");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("request_path");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id")
                        .HasName("pk_exception_logs");

                    b.HasIndex("ExceptionType")
                        .HasDatabaseName("ix_exception_logs_exception_type");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_exception_logs_occurred_on_utc");

                    b.ToTable("exception_logs", "public");
                });

            modelBuilder.Entity("Domain.Entities.TradingTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ActualEntryPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_entry_price");

                    b.Property<decimal?>("ActualExitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_exit_price");

                    b.Property<string>("AlpacaExitOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alpaca_exit_order_id");

                    b.Property<string>("AlpacaExitOrderPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("alpaca_exit_order_payload_json");

                    b.Property<string>("AlpacaExitOrderStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("alpaca_exit_order_status");

                    b.Property<string>("AlpacaOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alpaca_order_id");

                    b.Property<string>("AlpacaOrderPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("alpaca_order_payload_json");

                    b.Property<string>("AlpacaOrderStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("alpaca_order_status");

                    b.Property<string>("AlpacaStopLossOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alpaca_stop_loss_order_id");

                    b.Property<string>("AlpacaTakeProfitOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("alpaca_take_profit_order_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset?>("EntryFilledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_filled_at_utc");

                    b.Property<DateTimeOffset?>("ExitFilledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_filled_at_utc");

                    b.Property<string>("ExitReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("exit_reason");

                    b.Property<decimal>("PlannedEntryPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("planned_entry_price");

                    b.Property<decimal>("PlannedRiskPerUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("planned_risk_per_unit");

                    b.Property<decimal>("PlannedStopLossPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("planned_stop_loss_price");

                    b.Property<decimal>("PlannedTakeProfitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("planned_take_profit_price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("RealizedProfitLoss")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("realized_profit_loss");

                    b.Property<decimal?>("RealizedRMultiple")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("realized_r_multiple");

                    b.Property<int?>("RetestScore")
                        .HasColumnType("integer")
                        .HasColumnName("retest_score");

                    b.Property<int?>("SentimentScore")
                        .HasColumnType("integer")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("SignalInsightsJson")
                        .HasColumnType("text")
                        .HasColumnName("signal_insights_json");

                    b.Property<DateTimeOffset?>("SignalRetestBarTimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signal_retest_bar_timestamp_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_trading_trades");

                    b.HasIndex("AlpacaOrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_trading_trades_alpaca_order_id");

                    b.HasIndex("Symbol", "SubmittedAtUtc")
                        .HasDatabaseName("ix_trading_trades_symbol_submitted_at_utc");

                    b.ToTable("trading_trades", "public");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<NpgsqlTsVector>("DisplayNameSearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("display_name_search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "german")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "DisplayName" });

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SignInSecret")
                        .HasColumnType("text")
                        .HasColumnName("sign_in_secret");

                    b.Property<int?>("SignInTries")
                        .HasColumnType("integer")
                        .HasColumnName("sign_in_tries");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("DisplayNameSearchVector")
                        .HasDatabaseName("ix_user_display_name_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayNameSearchVector"), "GIN");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_user_phone_number");

                    b.ToTable("user", "public");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("BlockedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("blocked_user_id");

                    b.HasKey("UserId", "BlockedUserId")
                        .HasName("pk_user_block");

                    b.HasIndex("BlockedUserId")
                        .HasDatabaseName("ix_user_block_blocked_user_id");

                    b.ToTable("user_block", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.HasOne("Domain.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.Chat.ChatMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_message_chat_message_reply_to_message_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoomUser", b =>
                {
                    b.HasOne("Domain.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Users")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.HasOne("Domain.Entities.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_blocked_user_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_user_id");

                    b.Navigation("BlockedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
