// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518061106_03_CareerFramework")]
    partial class _03_CareerFramework
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entry");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_log_entry_actor_user_id");

                    b.HasIndex("TenantId", "OccurredOn")
                        .HasDatabaseName("ix_audit_log_entry_tenant_id_occurred_on");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entry_tenant_id_entity_type_entity_id");

                    b.ToTable("audit_log_entry", "public");
                });

            modelBuilder.Entity("Domain.Entities.CareerLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<long>("JobFamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_career_level");

                    b.HasIndex("JobFamilyId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_career_level_job_family_id_order");

                    b.HasIndex("TenantId", "JobFamilyId")
                        .HasDatabaseName("ix_career_level_tenant_id_job_family_id");

                    b.ToTable("career_level", "public");
                });

            modelBuilder.Entity("Domain.Entities.CareerPathSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Band")
                        .HasColumnType("integer")
                        .HasColumnName("band");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<long?>("CurrentRoleProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_role_profile_id");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<int?>("GoalCompletionScore")
                        .HasColumnType("integer")
                        .HasColumnName("goal_completion_score");

                    b.Property<int?>("ReadinessScore")
                        .HasColumnType("integer")
                        .HasColumnName("readiness_score");

                    b.Property<DateTimeOffset>("ScoredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_on");

                    b.Property<int?>("SkillFitScore")
                        .HasColumnType("integer")
                        .HasColumnName("skill_fit_score");

                    b.Property<long?>("TargetRoleProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_role_profile_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<int?>("ValidationCoverageScore")
                        .HasColumnType("integer")
                        .HasColumnName("validation_coverage_score");

                    b.HasKey("Id")
                        .HasName("pk_career_path_snapshot");

                    b.HasIndex("CurrentRoleProfileId")
                        .HasDatabaseName("ix_career_path_snapshot_current_role_profile_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_career_path_snapshot_employee_id");

                    b.HasIndex("TargetRoleProfileId")
                        .HasDatabaseName("ix_career_path_snapshot_target_role_profile_id");

                    b.HasIndex("TenantId", "TargetRoleProfileId")
                        .HasDatabaseName("ix_career_path_snapshot_tenant_id_target_role_profile_id");

                    b.HasIndex("TenantId", "EmployeeId", "ScoredOn")
                        .HasDatabaseName("ix_career_path_snapshot_tenant_id_employee_id_scored_on");

                    b.ToTable("career_path_snapshot", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasColumnType("text")
                        .HasColumnName("attachment_type");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("attachment_url");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_message");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_message_chat_room_id");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("ix_chat_message_reply_to_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_message_user_id");

                    b.ToTable("chat_message", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_direct");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_chat_room");

                    b.ToTable("chat_room", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoomUser", b =>
                {
                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("ChatRoomId", "UserId")
                        .HasName("pk_chat_room_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_room_user_user_id");

                    b.ToTable("chat_room_user", "public");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentDepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_department_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_department");

                    b.HasIndex("ParentDepartmentId")
                        .HasDatabaseName("ix_department_parent_department_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_department_tenant_id_name");

                    b.ToTable("department", "public");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("employee_number");

                    b.Property<string>("ExternalSourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_source_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("first_name");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("last_name");

                    b.Property<long?>("ManagerEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_employee_id");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("ManagerEmployeeId")
                        .HasDatabaseName("ix_employee_manager_employee_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_employee_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_employee_user_id");

                    b.HasIndex("TenantId", "EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_tenant_id_employee_number");

                    b.HasIndex("TenantId", "ExternalSourceId")
                        .HasDatabaseName("ix_employee_tenant_id_external_source_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_tenant_id_user_id");

                    b.ToTable("employee", "public");
                });

            modelBuilder.Entity("Domain.Entities.EmployeeRoleProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AssignedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_on");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("RoleProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_profile_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_employee_role_profile");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_role_profile_employee_id");

                    b.HasIndex("RoleProfileId")
                        .HasDatabaseName("ix_employee_role_profile_role_profile_id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_role_profile_tenant_id_employee_id")
                        .HasFilter("is_active = true");

                    b.HasIndex("TenantId", "RoleProfileId")
                        .HasDatabaseName("ix_employee_role_profile_tenant_id_role_profile_id");

                    b.ToTable("employee_role_profile", "public");
                });

            modelBuilder.Entity("Domain.Entities.EmployeeSkillAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClaimedSkillLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("claimed_skill_level_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<string>("Evidence")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("evidence");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long?>("ValidatedByEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("validated_by_employee_id");

                    b.Property<DateTimeOffset?>("ValidatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_on");

                    b.Property<long?>("ValidatedSkillLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("validated_skill_level_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_skill_assessment");

                    b.HasIndex("ClaimedSkillLevelId")
                        .HasDatabaseName("ix_employee_skill_assessment_claimed_skill_level_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_employee_skill_assessment_skill_id");

                    b.HasIndex("ValidatedByEmployeeId")
                        .HasDatabaseName("ix_employee_skill_assessment_validated_by_employee_id");

                    b.HasIndex("ValidatedSkillLevelId")
                        .HasDatabaseName("ix_employee_skill_assessment_validated_skill_level_id");

                    b.HasIndex("EmployeeId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_skill_assessment_employee_id_skill_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_employee_skill_assessment_tenant_id_status");

                    b.ToTable("employee_skill_assessment", "public");
                });

            modelBuilder.Entity("Domain.Entities.ExceptionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CaptureKind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capture_kind");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("exception_type");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_handled");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("request_path");

                    b.Property<string>("Source")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id")
                        .HasName("pk_exception_logs");

                    b.HasIndex("ExceptionType")
                        .HasDatabaseName("ix_exception_logs_exception_type");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_exception_logs_occurred_on_utc");

                    b.ToTable("exception_logs", "public");
                });

            modelBuilder.Entity("Domain.Entities.Goal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_employee_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<decimal?>("CurrentValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("current_value");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long?>("TargetSkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_skill_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<decimal?>("TargetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("target_value");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_goal");

                    b.HasIndex("AuthorEmployeeId")
                        .HasDatabaseName("ix_goal_author_employee_id");

                    b.HasIndex("DueOn")
                        .HasDatabaseName("ix_goal_due_on");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_goal_employee_id");

                    b.HasIndex("TargetSkillId")
                        .HasDatabaseName("ix_goal_target_skill_id");

                    b.HasIndex("TenantId", "EmployeeId", "Status")
                        .HasDatabaseName("ix_goal_tenant_id_employee_id_status");

                    b.ToTable("goal", "public");
                });

            modelBuilder.Entity("Domain.Entities.GoalCheckIn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_employee_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long>("GoalId")
                        .HasColumnType("bigint")
                        .HasColumnName("goal_id");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("note");

                    b.Property<decimal?>("ProgressValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("progress_value");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_goal_check_in");

                    b.HasIndex("AuthorEmployeeId")
                        .HasDatabaseName("ix_goal_check_in_author_employee_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_goal_check_in_tenant_id");

                    b.HasIndex("GoalId", "CreatedOn")
                        .HasDatabaseName("ix_goal_check_in_goal_id_created_on");

                    b.ToTable("goal_check_in", "public");
                });

            modelBuilder.Entity("Domain.Entities.JobFamily", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_job_family");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_job_family_tenant_id_is_active");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_job_family_tenant_id_name");

                    b.ToTable("job_family", "public");
                });

            modelBuilder.Entity("Domain.Entities.LearningResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long?>("MediaFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_file_id");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("points_awarded");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_learning_resource");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_learning_resource_type");

                    b.HasIndex("TenantId", "Title")
                        .HasDatabaseName("ix_learning_resource_tenant_id_title");

                    b.ToTable("learning_resource", "public");
                });

            modelBuilder.Entity("Domain.Entities.RoleProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CareerLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("career_level_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("JobFamilyId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_role_profile");

                    b.HasIndex("CareerLevelId")
                        .HasDatabaseName("ix_role_profile_career_level_id");

                    b.HasIndex("JobFamilyId", "CareerLevelId")
                        .HasDatabaseName("ix_role_profile_job_family_id_career_level_id");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_role_profile_tenant_id_is_active");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_profile_tenant_id_name");

                    b.ToTable("role_profile", "public");
                });

            modelBuilder.Entity("Domain.Entities.RoleProfileSkillRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long>("RequiredSkillLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("required_skill_level_id");

                    b.Property<long>("RoleProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_profile_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_role_profile_skill_requirement");

                    b.HasIndex("RequiredSkillLevelId")
                        .HasDatabaseName("ix_role_profile_skill_requirement_required_skill_level_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_role_profile_skill_requirement_skill_id");

                    b.HasIndex("RoleProfileId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_profile_skill_requirement_role_profile_id_skill_id");

                    b.HasIndex("TenantId", "SkillId")
                        .HasDatabaseName("ix_role_profile_skill_requirement_tenant_id_skill_id");

                    b.ToTable("role_profile_skill_requirement", "public");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentSkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_skill_id");

                    b.Property<long>("SkillCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_category_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_skill");

                    b.HasIndex("ParentSkillId")
                        .HasDatabaseName("ix_skill_parent_skill_id");

                    b.HasIndex("SkillCategoryId")
                        .HasDatabaseName("ix_skill_skill_category_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_tenant_id_name");

                    b.ToTable("skill", "public");
                });

            modelBuilder.Entity("Domain.Entities.SkillCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_skill_category");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_category_tenant_id_name");

                    b.ToTable("skill_category", "public");
                });

            modelBuilder.Entity("Domain.Entities.SkillLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("PointsThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("points_threshold");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_skill_level");

                    b.HasIndex("SkillId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_level_skill_id_order");

                    b.ToTable("skill_level", "public");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<long?>("ManagerEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("manager_employee_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_team");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_team_department_id");

                    b.HasIndex("ManagerEmployeeId")
                        .HasDatabaseName("ix_team_manager_employee_id");

                    b.HasIndex("TenantId", "DepartmentId", "Name")
                        .HasDatabaseName("ix_team_tenant_id_department_id_name");

                    b.ToTable("team", "public");
                });

            modelBuilder.Entity("Domain.Entities.TeamSkillRequirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long>("RequiredSkillLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("required_skill_level_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_team_skill_requirement");

                    b.HasIndex("RequiredSkillLevelId")
                        .HasDatabaseName("ix_team_skill_requirement_required_skill_level_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_team_skill_requirement_skill_id");

                    b.HasIndex("TeamId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_skill_requirement_team_id_skill_id");

                    b.HasIndex("TenantId", "TeamId")
                        .HasDatabaseName("ix_team_skill_requirement_tenant_id_team_id");

                    b.ToTable("team_skill_requirement", "public");
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Plan")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_tenant_owner_user_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_slug");

                    b.ToTable("tenant", "public");
                });

            modelBuilder.Entity("Domain.Entities.TenantInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AcceptedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset?>("AcceptedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_on");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_tenant_invitation");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_invitation_token");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_tenant_invitation_tenant_id_email");

                    b.ToTable("tenant_invitation", "public");
                });

            modelBuilder.Entity("Domain.Entities.TenantMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("JoinedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_on");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_membership");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_membership_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_membership_tenant_id_user_id");

                    b.ToTable("tenant_membership", "public");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<NpgsqlTsVector>("DisplayNameSearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("display_name_search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "german")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "DisplayName" });

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_platform_admin");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SignInSecret")
                        .HasColumnType("text")
                        .HasColumnName("sign_in_secret");

                    b.Property<int?>("SignInTries")
                        .HasColumnType("integer")
                        .HasColumnName("sign_in_tries");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("DisplayNameSearchVector")
                        .HasDatabaseName("ix_user_display_name_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayNameSearchVector"), "GIN");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_user_phone_number");

                    b.ToTable("user", "public");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("BlockedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("blocked_user_id");

                    b.HasKey("UserId", "BlockedUserId")
                        .HasName("pk_user_block");

                    b.HasIndex("BlockedUserId")
                        .HasDatabaseName("ix_user_block_blocked_user_id");

                    b.ToTable("user_block", "public");
                });

            modelBuilder.Entity("Domain.Entities.CareerLevel", b =>
                {
                    b.HasOne("Domain.Entities.JobFamily", "JobFamily")
                        .WithMany("CareerLevels")
                        .HasForeignKey("JobFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_career_level_job_family_job_family_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_career_level_tenant_tenant_id");

                    b.Navigation("JobFamily");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.CareerPathSnapshot", b =>
                {
                    b.HasOne("Domain.Entities.RoleProfile", "CurrentRoleProfile")
                        .WithMany()
                        .HasForeignKey("CurrentRoleProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_career_path_snapshot_role_profile_current_role_profile_id");

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_career_path_snapshot_employee_employee_id");

                    b.HasOne("Domain.Entities.RoleProfile", "TargetRoleProfile")
                        .WithMany()
                        .HasForeignKey("TargetRoleProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_career_path_snapshot_role_profile_target_role_profile_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_career_path_snapshot_tenant_tenant_id");

                    b.Navigation("CurrentRoleProfile");

                    b.Navigation("Employee");

                    b.Navigation("TargetRoleProfile");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.HasOne("Domain.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.Chat.ChatMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_message_chat_message_reply_to_message_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoomUser", b =>
                {
                    b.HasOne("Domain.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Users")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.HasOne("Domain.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_department_department_parent_department_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_department_tenant_tenant_id");

                    b.Navigation("ParentDepartment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "ManagerEmployee")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_employee_employee_manager_employee_id");

                    b.HasOne("Domain.Entities.Team", "Team")
                        .WithMany("Employees")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employee_team_team_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_employee_tenant_tenant_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_user_user_id");

                    b.Navigation("ManagerEmployee");

                    b.Navigation("Team");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.EmployeeRoleProfile", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_role_profile_employee_employee_id");

                    b.HasOne("Domain.Entities.RoleProfile", "RoleProfile")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("RoleProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_role_profile_role_profile_role_profile_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_employee_role_profile_tenant_tenant_id");

                    b.Navigation("Employee");

                    b.Navigation("RoleProfile");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.EmployeeSkillAssessment", b =>
                {
                    b.HasOne("Domain.Entities.SkillLevel", "ClaimedSkillLevel")
                        .WithMany()
                        .HasForeignKey("ClaimedSkillLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_skill_assessment_skill_level_claimed_skill_level_id");

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_skill_assessment_employee_employee_id");

                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_skill_assessment_skill_skill_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_employee_skill_assessment_tenant_tenant_id");

                    b.HasOne("Domain.Entities.Employee", "ValidatedByEmployee")
                        .WithMany()
                        .HasForeignKey("ValidatedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employee_skill_assessment_employee_validated_by_employee_id");

                    b.HasOne("Domain.Entities.SkillLevel", "ValidatedSkillLevel")
                        .WithMany()
                        .HasForeignKey("ValidatedSkillLevelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employee_skill_assessment_skill_level_validated_skill_level");

                    b.Navigation("ClaimedSkillLevel");

                    b.Navigation("Employee");

                    b.Navigation("Skill");

                    b.Navigation("Tenant");

                    b.Navigation("ValidatedByEmployee");

                    b.Navigation("ValidatedSkillLevel");
                });

            modelBuilder.Entity("Domain.Entities.Goal", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "AuthorEmployee")
                        .WithMany()
                        .HasForeignKey("AuthorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goal_employee_author_employee_id");

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goal_employee_employee_id");

                    b.HasOne("Domain.Entities.Skill", "TargetSkill")
                        .WithMany()
                        .HasForeignKey("TargetSkillId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_goal_skill_target_skill_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_goal_tenant_tenant_id");

                    b.Navigation("AuthorEmployee");

                    b.Navigation("Employee");

                    b.Navigation("TargetSkill");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.GoalCheckIn", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "AuthorEmployee")
                        .WithMany()
                        .HasForeignKey("AuthorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goal_check_in_employee_author_employee_id");

                    b.HasOne("Domain.Entities.Goal", "Goal")
                        .WithMany("CheckIns")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goal_check_in_goal_goal_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_goal_check_in_tenant_tenant_id");

                    b.Navigation("AuthorEmployee");

                    b.Navigation("Goal");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.JobFamily", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_job_family_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.LearningResource", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_learning_resource_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.RoleProfile", b =>
                {
                    b.HasOne("Domain.Entities.CareerLevel", "CareerLevel")
                        .WithMany("RoleProfiles")
                        .HasForeignKey("CareerLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_profile_career_level_career_level_id");

                    b.HasOne("Domain.Entities.JobFamily", "JobFamily")
                        .WithMany("RoleProfiles")
                        .HasForeignKey("JobFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_profile_job_family_job_family_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_role_profile_tenant_tenant_id");

                    b.Navigation("CareerLevel");

                    b.Navigation("JobFamily");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.RoleProfileSkillRequirement", b =>
                {
                    b.HasOne("Domain.Entities.SkillLevel", "RequiredSkillLevel")
                        .WithMany()
                        .HasForeignKey("RequiredSkillLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_profile_skill_requirement_skill_level_required_skill_l");

                    b.HasOne("Domain.Entities.RoleProfile", "RoleProfile")
                        .WithMany("SkillRequirements")
                        .HasForeignKey("RoleProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_profile_skill_requirement_role_profile_role_profile_id");

                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_profile_skill_requirement_skill_skill_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_role_profile_skill_requirement_tenant_tenant_id");

                    b.Navigation("RequiredSkillLevel");

                    b.Navigation("RoleProfile");

                    b.Navigation("Skill");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.HasOne("Domain.Entities.Skill", "ParentSkill")
                        .WithMany("ChildSkills")
                        .HasForeignKey("ParentSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_skill_skill_parent_skill_id");

                    b.HasOne("Domain.Entities.SkillCategory", "SkillCategory")
                        .WithMany("Skills")
                        .HasForeignKey("SkillCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_skill_skill_category_skill_category_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_skill_tenant_tenant_id");

                    b.Navigation("ParentSkill");

                    b.Navigation("SkillCategory");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.SkillCategory", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_skill_category_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.SkillLevel", b =>
                {
                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany("SkillLevels")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_level_skill_skill_id");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Teams")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_department_department_id");

                    b.HasOne("Domain.Entities.Employee", "ManagerEmployee")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_team_employee_manager_employee_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_team_tenant_tenant_id");

                    b.Navigation("Department");

                    b.Navigation("ManagerEmployee");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.TeamSkillRequirement", b =>
                {
                    b.HasOne("Domain.Entities.SkillLevel", "RequiredSkillLevel")
                        .WithMany()
                        .HasForeignKey("RequiredSkillLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_skill_requirement_skill_level_required_skill_level_id");

                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_skill_requirement_skill_skill_id");

                    b.HasOne("Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_skill_requirement_team_team_id");

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_team_skill_requirement_tenant_tenant_id");

                    b.Navigation("RequiredSkillLevel");

                    b.Navigation("Skill");

                    b.Navigation("Team");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.HasOne("Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tenant_user_owner_user_id");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Domain.Entities.TenantInvitation", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_invitation_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Domain.Entities.TenantMembership", b =>
                {
                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_membership_tenant_tenant_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_membership_user_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.HasOne("Domain.Entities.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_blocked_user_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_user_id");

                    b.Navigation("BlockedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CareerLevel", b =>
                {
                    b.Navigation("RoleProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("DirectReports");
                });

            modelBuilder.Entity("Domain.Entities.Goal", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("Domain.Entities.JobFamily", b =>
                {
                    b.Navigation("CareerLevels");

                    b.Navigation("RoleProfiles");
                });

            modelBuilder.Entity("Domain.Entities.RoleProfile", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("SkillRequirements");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Navigation("ChildSkills");

                    b.Navigation("SkillLevels");
                });

            modelBuilder.Entity("Domain.Entities.SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("TenantMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
