// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316081157_AddAiFeatures")]
    partial class AddAiFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasColumnType("text")
                        .HasColumnName("attachment_type");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("attachment_url");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_message");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_message_chat_room_id");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("ix_chat_message_reply_to_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_message_user_id");

                    b.ToTable("chat_message", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_direct");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_chat_room");

                    b.ToTable("chat_room", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoomUser", b =>
                {
                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("ChatRoomId", "UserId")
                        .HasName("pk_chat_room_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_room_user_user_id");

                    b.ToTable("chat_room_user", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<string>>("Color")
                        .HasColumnType("text[]")
                        .HasColumnName("color");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("Cycle")
                        .HasColumnType("text")
                        .HasColumnName("cycle");

                    b.Property<string>("Effect")
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int?>("Might")
                        .HasColumnType("integer")
                        .HasColumnName("might");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Promo")
                        .HasColumnType("boolean")
                        .HasColumnName("promo");

                    b.Property<string>("Rarity")
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("SetName")
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_card");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_card_reference_id");

                    b.ToTable("riftbound_card", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChampionId")
                        .HasColumnType("bigint")
                        .HasColumnName("champion_id");

                    b.PrimitiveCollection<List<string>>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<long>("LegendId")
                        .HasColumnType("bigint")
                        .HasColumnName("legend_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck");

                    b.HasIndex("ChampionId")
                        .HasDatabaseName("ix_riftbound_deck_champion_id");

                    b.HasIndex("LegendId")
                        .HasDatabaseName("ix_riftbound_deck_legend_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_riftbound_deck_owner_id");

                    b.ToTable("riftbound_deck", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckBattlefield", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_battlefield");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_riftbound_deck_battlefield_card_id");

                    b.HasIndex("DeckId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_battlefield_deck_id_card_id");

                    b.ToTable("riftbound_deck_battlefield", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_card");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_riftbound_deck_card_card_id");

                    b.HasIndex("DeckId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_card_deck_id_card_id");

                    b.ToTable("riftbound_deck_card", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_comment");

                    b.HasIndex("DeckId")
                        .HasDatabaseName("ix_riftbound_deck_comment_deck_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_riftbound_deck_comment_parent_comment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_riftbound_deck_comment_user_id");

                    b.ToTable("riftbound_deck_comment", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckOptimizationCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<int>("Draws")
                        .HasColumnType("integer")
                        .HasColumnName("draws");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<decimal>("HeadToHeadScore")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("head_to_head_score");

                    b.Property<long>("LegendId")
                        .HasColumnType("bigint")
                        .HasColumnName("legend_id");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<int>("RankGlobal")
                        .HasColumnType("integer")
                        .HasColumnName("rank_global");

                    b.Property<int>("RankInLegend")
                        .HasColumnType("integer")
                        .HasColumnName("rank_in_legend");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<decimal>("SonnebornBerger")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("sonneborn_berger");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("win_rate");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_optimization_candidate");

                    b.HasIndex("DeckId")
                        .HasDatabaseName("ix_riftbound_deck_optimization_candidate_deck_id");

                    b.HasIndex("RunId", "Generation", "DeckId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_optimization_candidate_run_id_generation_dec");

                    b.HasIndex("RunId", "Generation", "RankGlobal")
                        .HasDatabaseName("ix_riftbound_deck_optimization_candidate_run_id_generation_ran");

                    b.HasIndex("RunId", "Generation", "LegendId", "RankInLegend")
                        .HasDatabaseName("ix_riftbound_deck_optimization_candidate_run_id_generation_leg");

                    b.ToTable("riftbound_deck_optimization_candidate", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckOptimizationMatchup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeckAId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_a_id");

                    b.Property<int>("DeckAWins")
                        .HasColumnType("integer")
                        .HasColumnName("deck_a_wins");

                    b.Property<long>("DeckBId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_b_id");

                    b.Property<int>("DeckBWins")
                        .HasColumnType("integer")
                        .HasColumnName("deck_b_wins");

                    b.Property<int>("Draws")
                        .HasColumnType("integer")
                        .HasColumnName("draws");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("games_played");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_optimization_matchup");

                    b.HasIndex("DeckAId")
                        .HasDatabaseName("ix_riftbound_deck_optimization_matchup_deck_a_id");

                    b.HasIndex("DeckBId")
                        .HasDatabaseName("ix_riftbound_deck_optimization_matchup_deck_b_id");

                    b.HasIndex("RunId", "Generation")
                        .HasDatabaseName("ix_riftbound_deck_optimization_matchup_run_id_generation");

                    b.HasIndex("RunId", "Generation", "DeckAId", "DeckBId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_optimization_matchup_run_id_generation_deck_");

                    b.ToTable("riftbound_deck_optimization_matchup", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckOptimizationRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int>("CurrentGeneration")
                        .HasColumnType("integer")
                        .HasColumnName("current_generation");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<int>("Generations")
                        .HasColumnType("integer")
                        .HasColumnName("generations");

                    b.Property<int>("MaxAutoplaySteps")
                        .HasColumnType("integer")
                        .HasColumnName("max_autoplay_steps");

                    b.Property<int>("PopulationSize")
                        .HasColumnType("integer")
                        .HasColumnName("population_size");

                    b.Property<decimal>("ProgressPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress_percent");

                    b.Property<long>("RequestedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by_user_id");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.Property<int>("SeedsPerMatch")
                        .HasColumnType("integer")
                        .HasColumnName("seeds_per_match");

                    b.Property<DateTimeOffset?>("StartedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_optimization_run");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_riftbound_deck_optimization_run_created_on");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_riftbound_deck_optimization_run_requested_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_riftbound_deck_optimization_run_status");

                    b.ToTable("riftbound_deck_optimization_run", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_rating");

                    b.HasIndex("DeckId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_rating_deck_id_user_id");

                    b.ToTable("riftbound_deck_rating", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckRune", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_rune");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_riftbound_deck_rune_card_id");

                    b.HasIndex("DeckId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_rune_deck_id_card_id");

                    b.ToTable("riftbound_deck_rune", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_share");

                    b.HasIndex("DeckId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_share_deck_id_user_id");

                    b.ToTable("riftbound_deck_share", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckSideboardCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_sideboard_card");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_riftbound_deck_sideboard_card_card_id");

                    b.HasIndex("DeckId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_sideboard_card_deck_id_card_id");

                    b.ToTable("riftbound_deck_sideboard_card", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundSimulationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<long>("SimulationRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("simulation_run_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_simulation_event");

                    b.HasIndex("SimulationRunId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_simulation_event_simulation_run_id_sequence");

                    b.ToTable("riftbound_simulation_event", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundSimulationRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChallengerDeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("challenger_deck_id");

                    b.Property<string>("ChallengerPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("challenger_policy");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<long>("OpponentDeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("opponent_deck_id");

                    b.Property<string>("OpponentPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("opponent_policy");

                    b.Property<long>("RequestedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("RulesetVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ruleset_version");

                    b.Property<string>("ScoreSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("score_summary_json");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<int?>("WinnerPlayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("winner_player_index");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_simulation_run");

                    b.HasIndex("ChallengerDeckId")
                        .HasDatabaseName("ix_riftbound_simulation_run_challenger_deck_id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_riftbound_simulation_run_created_on");

                    b.HasIndex("OpponentDeckId")
                        .HasDatabaseName("ix_riftbound_simulation_run_opponent_deck_id");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_riftbound_simulation_run_requested_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_riftbound_simulation_run_status");

                    b.ToTable("riftbound_simulation_run", "public");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<NpgsqlTsVector>("DisplayNameSearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("display_name_search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "german")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "DisplayName" });

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SignInSecret")
                        .HasColumnType("text")
                        .HasColumnName("sign_in_secret");

                    b.Property<int?>("SignInTries")
                        .HasColumnType("integer")
                        .HasColumnName("sign_in_tries");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("DisplayNameSearchVector")
                        .HasDatabaseName("ix_user_display_name_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayNameSearchVector"), "GIN");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_user_phone_number");

                    b.ToTable("user", "public");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("BlockedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("blocked_user_id");

                    b.HasKey("UserId", "BlockedUserId")
                        .HasName("pk_user_block");

                    b.HasIndex("BlockedUserId")
                        .HasDatabaseName("ix_user_block_blocked_user_id");

                    b.ToTable("user_block", "public");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.HasOne("Domain.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.Chat.ChatMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_message_chat_message_reply_to_message_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoomUser", b =>
                {
                    b.HasOne("Domain.Entities.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Users")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeck", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_riftbound_card_champion_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Legend")
                        .WithMany()
                        .HasForeignKey("LegendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_riftbound_card_legend_id");

                    b.HasOne("Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_user_owner_id");

                    b.Navigation("Champion");

                    b.Navigation("Legend");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckBattlefield", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_battlefield_riftbound_card_card_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Battlefields")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_battlefield_riftbound_deck_deck_id");

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckCard", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_card_riftbound_card_card_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_card_riftbound_deck_deck_id");

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckComment", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Comments")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_comment_riftbound_deck_deck_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeckComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_riftbound_deck_comment_riftbound_deck_comment_parent_commen");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_comment_user_user_id");

                    b.Navigation("Deck");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckOptimizationCandidate", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_optimization_candidate_riftbound_deck_deck_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeckOptimizationRun", "Run")
                        .WithMany("Candidates")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_optimization_candidate_riftbound_deck_optimi");

                    b.Navigation("Deck");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckOptimizationMatchup", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "DeckA")
                        .WithMany()
                        .HasForeignKey("DeckAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_optimization_matchup_riftbound_deck_deck_a_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "DeckB")
                        .WithMany()
                        .HasForeignKey("DeckBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_optimization_matchup_riftbound_deck_deck_b_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeckOptimizationRun", "Run")
                        .WithMany("Matchups")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_optimization_matchup_riftbound_deck_optimiza");

                    b.Navigation("DeckA");

                    b.Navigation("DeckB");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckOptimizationRun", b =>
                {
                    b.HasOne("Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_optimization_run_user_requested_by_user_id");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckRating", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Ratings")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_rating_riftbound_deck_deck_id");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckRune", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_rune_riftbound_card_card_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Runes")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_rune_riftbound_deck_deck_id");

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckShare", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Shares")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_share_riftbound_deck_deck_id");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckSideboardCard", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_sideboard_card_riftbound_card_card_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("SideboardCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_sideboard_card_riftbound_deck_deck_id");

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundSimulationEvent", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundSimulationRun", "SimulationRun")
                        .WithMany("Events")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_simulation_event_riftbound_simulation_run_simulat");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundSimulationRun", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "ChallengerDeck")
                        .WithMany()
                        .HasForeignKey("ChallengerDeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_simulation_run_riftbound_deck_challenger_deck_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "OpponentDeck")
                        .WithMany()
                        .HasForeignKey("OpponentDeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_simulation_run_riftbound_deck_opponent_deck_id");

                    b.HasOne("Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_simulation_run_user_requested_by_user_id");

                    b.Navigation("ChallengerDeck");

                    b.Navigation("OpponentDeck");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.HasOne("Domain.Entities.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_blocked_user_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_user_id");

                    b.Navigation("BlockedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Domain.Entities.Chat.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeck", b =>
                {
                    b.Navigation("Battlefields");

                    b.Navigation("Cards");

                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("Runes");

                    b.Navigation("Shares");

                    b.Navigation("SideboardCards");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckOptimizationRun", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Matchups");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundSimulationRun", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
