// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasColumnType("text")
                        .HasColumnName("attachment_type");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text")
                        .HasColumnName("attachment_url");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_message");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_chat_message_chat_room_id");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("ix_chat_message_reply_to_message_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_message_user_id");

                    b.ToTable("chat_message", "public");
                });

            modelBuilder.Entity("Domain.Entities.ChatRoom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_direct");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_chat_room");

                    b.ToTable("chat_room", "public");
                });

            modelBuilder.Entity("Domain.Entities.ChatRoomUser", b =>
                {
                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.HasKey("ChatRoomId", "UserId")
                        .HasName("pk_chat_room_user");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_room_user_user_id");

                    b.ToTable("chat_room_user", "public");
                });

            modelBuilder.Entity("Domain.Entities.Habit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("HabitPreparationId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_preparation_id");

                    b.Property<bool>("IsPreparationHabit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preparation_habit");

                    b.Property<string>("Motivation")
                        .HasColumnType("text")
                        .HasColumnName("motivation");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<NpgsqlTsVector>("TitleSearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("title_search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "English")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title" });

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_habit");

                    b.HasIndex("HabitPreparationId")
                        .HasDatabaseName("ix_habit_habit_preparation_id");

                    b.HasIndex("TitleSearchVector")
                        .HasDatabaseName("ix_habit_title_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TitleSearchVector"), "GIN");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_habit_user_id");

                    b.ToTable("habit", "public");
                });

            modelBuilder.Entity("Domain.Entities.HabitHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("now() AT TIME ZONE 'UTC'");

                    b.Property<long?>("HabitHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_history_id");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    b.Property<long?>("HabitTimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_time_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_habit_history");

                    b.HasIndex("HabitHistoryId")
                        .HasDatabaseName("ix_habit_history_habit_history_id");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("ix_habit_history_habit_id");

                    b.HasIndex("HabitTimeId")
                        .HasDatabaseName("ix_habit_history_habit_time_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_habit_history_user_id");

                    b.ToTable("habit_history", "public");
                });

            modelBuilder.Entity("Domain.Entities.HabitTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval")
                        .HasColumnName("time");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_habit_time");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("ix_habit_time_habit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_habit_time_user_id");

                    b.ToTable("habit_time", "public");
                });

            modelBuilder.Entity("Domain.Entities.HabitTrigger", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("HabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("habit_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long?>("TriggerHabitId")
                        .HasColumnType("bigint")
                        .HasColumnName("trigger_habit_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_habit_trigger");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("ix_habit_trigger_habit_id");

                    b.HasIndex("TriggerHabitId")
                        .HasDatabaseName("ix_habit_trigger_trigger_habit_id");

                    b.ToTable("habit_trigger", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<List<string>>("Color")
                        .HasColumnType("text[]")
                        .HasColumnName("color");

                    b.Property<int?>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("Cycle")
                        .HasColumnType("text")
                        .HasColumnName("cycle");

                    b.Property<string>("Effect")
                        .HasColumnType("text")
                        .HasColumnName("effect");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int?>("Might")
                        .HasColumnType("integer")
                        .HasColumnName("might");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Promo")
                        .HasColumnType("boolean")
                        .HasColumnName("promo");

                    b.Property<string>("Rarity")
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("SetName")
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_card");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_card_reference_id");

                    b.ToTable("riftbound_card", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChampionId")
                        .HasColumnType("bigint")
                        .HasColumnName("champion_id");

                    b.PrimitiveCollection<List<string>>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<long>("LegendId")
                        .HasColumnType("bigint")
                        .HasColumnName("legend_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck");

                    b.HasIndex("ChampionId")
                        .HasDatabaseName("ix_riftbound_deck_champion_id");

                    b.HasIndex("LegendId")
                        .HasDatabaseName("ix_riftbound_deck_legend_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_riftbound_deck_owner_id");

                    b.ToTable("riftbound_deck", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_card");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_riftbound_deck_card_card_id");

                    b.HasIndex("DeckId", "CardId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_card_deck_id_card_id");

                    b.ToTable("riftbound_deck_card", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_comment");

                    b.HasIndex("DeckId")
                        .HasDatabaseName("ix_riftbound_deck_comment_deck_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_riftbound_deck_comment_parent_comment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_riftbound_deck_comment_user_id");

                    b.ToTable("riftbound_deck_comment", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_rating");

                    b.HasIndex("DeckId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_rating_deck_id_user_id");

                    b.ToTable("riftbound_deck_rating", "public");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_riftbound_deck_share");

                    b.HasIndex("DeckId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_riftbound_deck_share_deck_id_user_id");

                    b.ToTable("riftbound_deck_share", "public");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset>("DeletedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<NpgsqlTsVector>("DisplayNameSearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("display_name_search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "german")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "DisplayName" });

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SignInSecret")
                        .HasColumnType("text")
                        .HasColumnName("sign_in_secret");

                    b.Property<int?>("SignInTries")
                        .HasColumnType("integer")
                        .HasColumnName("sign_in_tries");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("DisplayNameSearchVector")
                        .HasDatabaseName("ix_user_display_name_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayNameSearchVector"), "GIN");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_user_phone_number");

                    b.ToTable("user", "public");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("BlockedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("blocked_user_id");

                    b.HasKey("UserId", "BlockedUserId")
                        .HasName("pk_user_block");

                    b.HasIndex("BlockedUserId")
                        .HasDatabaseName("ix_user_block_blocked_user_id");

                    b.ToTable("user_block", "public");
                });

            modelBuilder.Entity("Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.ChatMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_message_chat_message_reply_to_message_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ChatRoomUser", b =>
                {
                    b.HasOne("Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Users")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_chat_room_chat_room_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_room_user_user_user_id");

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Habit", b =>
                {
                    b.HasOne("Domain.Entities.Habit", "Base")
                        .WithMany("Preparations")
                        .HasForeignKey("HabitPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_habit_habit_habit_preparation_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_user_user_id");

                    b.Navigation("Base");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.HabitHistory", b =>
                {
                    b.HasOne("Domain.Entities.HabitHistory", "CreatedByHistory")
                        .WithMany()
                        .HasForeignKey("HabitHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_habit_history_habit_history_habit_history_id");

                    b.HasOne("Domain.Entities.Habit", "Habit")
                        .WithMany("History")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_history_habit_habit_id");

                    b.HasOne("Domain.Entities.HabitTime", "CreatedByHabitTime")
                        .WithMany()
                        .HasForeignKey("HabitTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_habit_history_habit_time_habit_time_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("HabitHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_history_user_user_id");

                    b.Navigation("CreatedByHabitTime");

                    b.Navigation("CreatedByHistory");

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.HabitTime", b =>
                {
                    b.HasOne("Domain.Entities.Habit", "Habit")
                        .WithMany("Times")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_time_habit_habit_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("HabitTimes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_time_user_user_id");

                    b.Navigation("Habit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.HabitTrigger", b =>
                {
                    b.HasOne("Domain.Entities.Habit", "Habit")
                        .WithMany("Triggers")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_habit_trigger_habit_habit_id");

                    b.HasOne("Domain.Entities.Habit", "TriggerHabit")
                        .WithMany()
                        .HasForeignKey("TriggerHabitId")
                        .HasConstraintName("fk_habit_trigger_habit_trigger_habit_id");

                    b.Navigation("Habit");

                    b.Navigation("TriggerHabit");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeck", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_riftbound_card_champion_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Legend")
                        .WithMany()
                        .HasForeignKey("LegendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_riftbound_card_legend_id");

                    b.HasOne("Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_user_owner_id");

                    b.Navigation("Champion");

                    b.Navigation("Legend");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckCard", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_card_riftbound_card_card_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_card_riftbound_deck_deck_id");

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckComment", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Comments")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_comment_riftbound_deck_deck_id");

                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeckComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_riftbound_deck_comment_riftbound_deck_comment_parent_commen");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_comment_user_user_id");

                    b.Navigation("Deck");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckRating", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Ratings")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_rating_riftbound_deck_deck_id");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckShare", b =>
                {
                    b.HasOne("Domain.Entities.Riftbound.RiftboundDeck", "Deck")
                        .WithMany("Shares")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riftbound_deck_share_riftbound_deck_deck_id");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Domain.Entities.UserBlock", b =>
                {
                    b.HasOne("Domain.Entities.User", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_blocked_user_id");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_block_user_user_id");

                    b.Navigation("BlockedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ChatMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Domain.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Habit", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Preparations");

                    b.Navigation("Times");

                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeck", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Domain.Entities.Riftbound.RiftboundDeckComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("HabitHistory");

                    b.Navigation("HabitTimes");

                    b.Navigation("Habits");
                });
#pragma warning restore 612, 618
        }
    }
}
